"""tapd: user.tapd_nick, project.tapd_workspace_id

Revision ID: b89da7c4730a
Revises: 1e517d0cd9db
Create Date: 2026-07-08 15:31:32.913968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b89da7c4730a'
down_revision: Union[str, None] = '1e517d0cd9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('tapd_workspace_id', sa.String(length=32), server_default='', nullable=False))
    op.add_column('user', sa.Column('tapd_nick', sa.String(length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tapd_nick')
    op.drop_column('project', 'tapd_workspace_id')
    # ### end Alembic commands ###
