"""tapd sync: external source fields

Revision ID: 3b941c3aef6c
Revises: 6762071f3e6e
Create Date: 2026-07-08 15:31:18.638138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3b941c3aef6c'
down_revision: Union[str, None] = '6762071f3e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('source', sa.String(length=16), server_default='native', nullable=False))
    op.add_column('requirement', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.add_column('requirement', sa.Column('external_url', sa.String(length=512), server_default='', nullable=False))
    op.add_column('requirement', sa.Column('external_status', sa.String(length=64), server_default='', nullable=False))
    op.add_column('requirement', sa.Column('assignee', sa.String(length=255), server_default='', nullable=False))
    op.add_column('requirement', sa.Column('external_extra', sa.Text(), nullable=True))
    op.add_column('requirement', sa.Column('synced_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_requirement_source'), 'requirement', ['source'], unique=False)
    op.create_unique_constraint('uq_requirement_source_external', 'requirement', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_requirement_source_external', 'requirement', type_='unique')
    op.drop_index(op.f('ix_requirement_source'), table_name='requirement')
    op.drop_column('requirement', 'synced_at')
    op.drop_column('requirement', 'external_extra')
    op.drop_column('requirement', 'assignee')
    op.drop_column('requirement', 'external_status')
    op.drop_column('requirement', 'external_url')
    op.drop_column('requirement', 'external_id')
    op.drop_column('requirement', 'source')
    # ### end Alembic commands ###
