"""init: requirement, flow_event, review, analysis_run

Revision ID: 6762071f3e6e
Revises: 
Create Date: 2026-07-07 17:51:47.891033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6762071f3e6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('req_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('complexity', sa.String(length=8), nullable=True),
    sa.Column('expected_online_date', sa.Date(), nullable=True),
    sa.Column('source_context', sa.Text(), nullable=False),
    sa.Column('creator', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_parent_id'), 'requirement', ['parent_id'], unique=False)
    op.create_index(op.f('ix_requirement_project_id'), 'requirement', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirement_status'), 'requirement', ['status'], unique=False)
    op.create_table('analysis_run',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('complexity', sa.String(length=8), nullable=True),
    sa.Column('report_md', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_run_requirement_id'), 'analysis_run', ['requirement_id'], unique=False)
    op.create_table('flow_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=True),
    sa.Column('artifact_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_event_requirement_id'), 'flow_event', ['requirement_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('requirement_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('initiator', sa.String(length=64), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('participants', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('conclusion', sa.String(length=16), nullable=True),
    sa.Column('conclusion_comment', sa.Text(), nullable=False),
    sa.Column('concluded_by', sa.String(length=64), nullable=True),
    sa.Column('concluded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_requirement_id'), 'review', ['requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_requirement_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_flow_event_requirement_id'), table_name='flow_event')
    op.drop_table('flow_event')
    op.drop_index(op.f('ix_analysis_run_requirement_id'), table_name='analysis_run')
    op.drop_table('analysis_run')
    op.drop_index(op.f('ix_requirement_status'), table_name='requirement')
    op.drop_index(op.f('ix_requirement_project_id'), table_name='requirement')
    op.drop_index(op.f('ix_requirement_parent_id'), table_name='requirement')
    op.drop_table('requirement')
    # ### end Alembic commands ###
